version: '3.1'

services:

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx/config:/etc/nginx/conf.d
      - $PWD/frontend:/usr/share/nginx/html
      - $PWD/nginx/log:/var/log/nginx

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}      
    volumes: 
      - grafana-storage:/var/lib/grafana
      - $PWD/grafana:/etc/grafana/provisioning/
      - $PWD/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini

  node-red:
    build: $PWD/node-red
    restart: always
    ports:
      - 1880:1880
    volumes:
      - nodered-storage:/data

  influx:
    image: influxdb:latest
    restart: always
    environment:
      - INFLUXDB_DB=demo
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - 8086:8086
    volumes: 
      - influxdb-storage:/var/lib/influxdb

  plc-simulator:
    image: hzei/plc-simulator:latest
    restart: always
    ports: 
      - 4840:4840


volumes:
  grafana-storage:
  influxdb-storage:
  nodered-storage:
